module.exports = {
  ping: require("./commands/Bot Commands/ping.js"),
  randomUser: require("./commands/Fun Commands/randomUser.js"),
  say: require("./commands/Fun Commands/say.js"),
  hao: require("./commands/Questionable Commands/hao.js"),
  be: require("./commands/Bot Commands/be.js"),
  choose: require("./commands/Utility Commands/choose.js"),
  weather: require("./commands/Utility Commands/weather.js"),
  handpic: require("./commands/Questionable Commands/handpic.js"),
  bitcoin: require("./commands/Questionable Commands/bitcoin.js"),
  repository: require("./commands/Bot Commands/repository.js"),
  come: require("./commands/Questionable Commands/come"),
  commandList: require("./commands/Bot Commands/commandList.js"),
  copy_paste: require("./commands/Fun Commands/copy_paste.js"),
  wipeout: require("./commands/Questionable Commands/wipeout.js"),
  everyonePing: require("./commands/Questionable Commands/everyonePing.js"),
  setAvatar: require("./commands/Bot Commands/setAvatar.js"),
  pinnedMessages: require("./commands/Utility Commands/pinnedMessages.js")
};
